<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c544dac8-e7b8-483c-93d1-a46857f04ac3}" SpecialFunc="None">
    <Declaration><![CDATA[// Author RL
PROGRAM MAIN
VAR
	ForkliftControl : FB_XYZ_Movement;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Execute the entire system
ForkliftControl(Axis1 := GVL_Motion.Axis1, Axis2 := GVL_Motion.Axis2);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="621" Count="0" />
      <LineId Id="602" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>