<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c544dac8-e7b8-483c-93d1-a46857f04ac3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    // Clean slate - no variables needed here for now!
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Unconditionally call the background power and homing hardware engine
PRG_Hardware();
PRG_Manual_Drive();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="598" Count="0" />
      <LineId Id="519" Count="0" />
      <LineId Id="602" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>